import React from "react";
import { Link, useParams, Navigate } from "react-router-dom";
import { LuSparkles, LuArrowLeft } from "react-icons/lu";
import { Container } from "../../components/ui/primitives";
import Footer from "../../components/Layouts/Footer";

const CONTENT = {
  about: {
    title: "About InterviewEdge",
    intro: "InterviewEdge is an AI-powered interview preparation platform that helps candidates practice smarter.",
    sections: [
      { h: "Our mission", p: "We believe great candidates shouldn't lose offers to nerves or under-preparation. InterviewEdge gives everyone access to a personal AI coach that generates role-specific questions, runs realistic timed mocks, and gives honest, structured feedback." },
      { h: "How it works", p: "Generate a tailored question set for any role, reveal model answers when you're ready, dig into AI explanations, then test yourself with a timed mock interview that scores each answer and produces a full debrief." },
      { h: "Who it's for", p: "From new grads to senior engineers, PMs to designers — any role, any experience level. The questions adapt to you." },
    ],
  },
  careers: {
    title: "Careers",
    intro: "We're a small, fast-moving team building the future of interview prep.",
    sections: [
      { h: "Why join us", p: "Work on a product people genuinely love, with AI at its core and a direct line from your work to real candidate outcomes." },
      { h: "Open roles", p: "We don't have public openings listed right now, but we're always happy to hear from exceptional engineers, designers, and educators. Reach out and tell us what you'd build." },
    ],
  },
  privacy: {
    title: "Privacy Policy",
    intro: "Your data is yours. This summary explains what we store and why.",
    sections: [
      { h: "What we store", p: "Account details (name, email), the interview sessions and questions you generate, your mock-interview answers and scores, and basic usage data to improve the product." },
      { h: "How it's used", p: "Your content is used to power your experience — generating questions, scoring answers, and showing your analytics. We do not sell your personal data." },
      { h: "Your control", p: "You can delete any session at any time, which permanently removes its questions. Contact us to delete your account entirely." },
    ],
  },
  terms: {
    title: "Terms of Service",
    intro: "By using InterviewEdge you agree to these terms.",
    sections: [
      { h: "Acceptable use", p: "Use the platform for personal interview preparation. Don't abuse the AI endpoints, attempt to disrupt the service, or use it for unlawful purposes." },
      { h: "AI-generated content", p: "Questions, answers, and feedback are generated by AI and may contain errors. Treat them as practice material, not authoritative guidance." },
      { h: "No guarantees", p: "We provide the service \"as is.\" Preparation improves your odds, but we can't guarantee interview outcomes." },
    ],
  },
};

const InfoPage = ({ slug: slugProp }) => {
  const { slug: slugParam } = useParams();
  const slug = slugProp || slugParam;
  const data = CONTENT[slug];
  if (!data) return <Navigate to="/" replace />;

  return (
    <div className="bg-white min-h-screen flex flex-col">
      <nav className="sticky top-0 z-40 glass border-b border-slate-100">
        <Container className="h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-indigo-600 to-violet-600 flex items-center justify-center shadow-glow">
              <LuSparkles className="text-white" size={18} />
            </div>
            <span className="text-lg font-extrabold tracking-tight">
              Interview<span className="gradient-text">Edge</span>
            </span>
          </Link>
          <Link to="/" className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-600 hover:text-indigo-600">
            <LuArrowLeft size={16} /> Back home
          </Link>
        </Container>
      </nav>

      <Container className="py-14 flex-1 max-w-3xl">
        <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 tracking-tight">{data.title}</h1>
        <p className="text-lg text-slate-500 mt-3 leading-relaxed">{data.intro}</p>
        <div className="mt-10 space-y-8">
          {data.sections.map((s) => (
            <div key={s.h}>
              <h2 className="text-lg font-bold text-slate-900">{s.h}</h2>
              <p className="text-slate-600 mt-2 leading-relaxed">{s.p}</p>
            </div>
          ))}
        </div>
        <p className="text-xs text-slate-400 mt-12">Last updated {new Date().getFullYear()}.</p>
      </Container>

      <Footer />
    </div>
  );
};

export default InfoPage;
